/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KzOYuPVcSrL
 */
import { Input } from "@/components/ui/input";
import { Button } from "./ui/button";

export function Initial() {
  return (
    <div className=" bg-white px-4 flex-1 flex flex-col items-center justify-center space-y-4 text-center">
      <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl lg:text-6xl/none text-[#000000]">
        Para @sabrexe
      </h1>
      <p className="mx-auto max-w-[600px] text-gray-500 dark:text-gray-400">
        Se as luzes se apagarem... 🧙‍♂️
      </p>
      <div className="w-full max-w-md">
        <form action="">
          <div className="flex gap-3">
            <Input
              className="w-full bg-[#000000] text-white border mb-3 border-[#0D1026] rounded-md px-4 py-2 focus:outline-none focus:ring focus:ring-[#0D1026] dark:bg-gray-800 dark:focus:ring-gray-600"
              placeholder="Digite a magia certa..."
              type="text"
            />
            <Button type="submit">Soltar magia</Button>
          </div>
        </form>
      </div>
    </div>
  );
}
